/* istanbul ignore file */

export default {
    FETCH_ALBUMS_START: 'FETCH_ALBUMS_START',
    FETCH_ALBUMS_FULFILLED_VALID: 'FETCH_ALBUMS_FULFILLED_VALID',
    FETCH_ALBUMS_FULFILLED_INVALID: 'FETCH_ALBUMS_FULFILLED_INVALID',
    FETCH_ALBUMS_REJECTED: 'FETCH_ALBUMS_REJECTED',
    RESET_ALBUMS_STATE: 'RESET_ALBUMS_STATE',
};
